#!/bin/bash

#echo "[INITIALIZING] Zipping files..."
# Compress all the nessary files to be sent make sure all files accounted for
#zip -r -q PharmacyDatabase.zip DB2Files/ > /dev/null

#Send to turing then connect to turing
echo "[INITIALIZING] Loading files into turning directory."
echo -n "[INITIALIZING] Please enter your SCS User name: " ; read user
scp PharmacyDatabase.zip Pharmacy $user@turing.acs.ryerson.ca:~/ > /dev/null
echo "[INITIALIZING] Files loaded."
echo "[INITIALIZING] Connecting to turing."
ssh $user@turing.acs.ryerson.ca './Pharmacy'
 
