#!/bin/ksh

db2 connect to db2data > /dev/null

echo "[DB2] Creating Tables..."

db2 "CREATE TABLE Employee(
	Employee_PK integer NOT NULL,
	Employee_Name varchar(25) NOT NULL,
	Employee_Email varchar(45),
	Employee_Login varchar(25) NOT NULL,
	Employee_Password varchar(25) NOT NULL,
	Employee_Secret_Q varchar(25),
	Employee_Secret_Answer varchar(200),
	Employee_Security_Level_1_100 integer NOT NULL,
	Employee_Can_Write smallint NOT NULL,
	Employee_Can_Read smallint NOT NULL,
	PRIMARY KEY(Employee_PK)
)"

db2 "CREATE TABLE Product(
	Product_PK integer NOT NULL,
	Product_Number integer NOT NULL,
	Product_Name varchar(25) NOT NULL,
	Product_Initial_Price double,
	Product_Sale_Price double NOT NULL,
	Product_Qty integer NOT NULL,
	Product_Expiry_Date date,
	Product_Location_1 varchar(25),
	Product_Location_2 varchar(25),
	Product_In_Date date NOT NULL,
	Product_Out_Date date,
	PRIMARY KEY(Product_PK)
)"

db2 "CREATE TABLE OrderSet(
	OrderSet_PK integer NOT NULL,
	Order_Is_Delivered smallint NOT NULL,
	Order_Date date NOT NULL,
	PRIMARY KEY(OrderSet_PK)
)"

db2 "CREATE TABLE Customer(
	Customer_PK integer NOT NULL,
	Customer_OrdersSet_FK integer NOT NULL,
	Customer_Name varchar(25) NOT NULL,
	Customer_Email varchar(45),
	Customer_Money_Spent double NOT NULL,
	Customer_Shipping_Address varchar(75),
	Customer_Credit_Card varchar(30),
	PRIMARY KEY(Customer_PK),
	FOREIGN KEY (Customer_OrdersSet_FK) REFERENCES OrderSet(OrderSet_PK)
)"

db2 "CREATE TABLE Order(
	Orders_PK integer NOT NULL,
	Orders_OrderSet_FK integer NOT NULL,
	Order_Product_FK integer NOT NULL,
	Order_Qty integer NOT NULL,
	PRIMARY KEY(Orders_PK),
	FOREIGN KEY (Orders_OrderSet_FK) REFERENCES OrderSet(OrderSet_PK),
	FOREIGN KEY (Order_Product_FK) REFERENCES Product(Product_PK)
)"

db2 "CREATE TABLE Prescription(
	Prescription_PK integer NOT NULL,
	Prescription_Customer_FK integer NOT NULL,
	Prescription_Product_FK integer NOT NULL,
	Prescription_Employee_FK integer NOT NULL,
	Prescription_Qty integer NOT NULL,
	Prescription_Doctor varchar(35),
	Prescription_Quantity_Left integer NOT NULL,
	Prescription_Transaction_Number integer NOT NULL,
	PRIMARY KEY(Prescription_PK),
	FOREIGN KEY (Prescription_Customer_FK) REFERENCES Customer(Customer_PK),
	FOREIGN KEY (Prescription_Product_FK) REFERENCES Product(Product_PK),
	FOREIGN KEY (Prescription_Employee_FK) REFERENCES Employee(Employee_PK)
)"

db2 "CREATE TABLE IncomeStatement(
	IncomeStatement_PK integer NOT NULL,
	IncomeStatement_Sales_Total double,
	IncomeStatement_Net_Purchases double,
	IncomeStatement_Selling_Expenses double,
	IncomeStatement_Operations_Expenses double,
	IncomeStatement_Other_Revenue double,
	IncomeStatement_BalanceStatement_flag varchar(25),
	IncomeStatement_Date date NOT NULL,
	PRIMARY KEY(IncomeStatement_PK)
)"

db2 "CREATE TABLE Equity(
	Equity_PK integer NOT NULL,
	Equity_Date_Updated date NOT NULL,
	Equity_Previous_Equity_Sum	double,
	Equity_Sum double,
	Equity_New_Equity_Total double,
	PRIMARY KEY(Equity_PK)
)"

db2 "CREATE TABLE BalanceSheet(
	Balance_Sheet_PK integer NOT NULL,
	Balance_Sheet_Current_Assets double,
	Balance_Sheet_Short_Term_Assets double,
	Balance_Sheet_Property varchar(25) NOT NULL,
	Balance_Sheet_Long_Term_Assets double,
	Balance_Sheet_Current_Liabilities double,
	Balance_Sheet_Short_Term_Liabilities double,
	Balance_Sheet_Long_Term_Liabilities double,
	Balance_Sheet_Date date NOT NULL,
	Balance_Sheet_Intangible_Asset varchar(25),
	PRIMARY KEY(Balance_Sheet_PK)
)" 

echo "[DB2] Creating Tables: Done"
