#!/bin/ksh
#DB2 Pharmacy - Cashier Script

db2 connect to db2data > /dev/null

SELECTION=-1
# Will print infinitely until the user enters 0 to exit the previous Script.
while [ $SELECTION -ne 0 ]
do
	SELECTION=-1
	#Print Cashier Menu
	echo "----<CASHIER MENU>----"
	echo "1 | Price of a product"
	echo "2 | Query 2"
	echo "3 | Query 3"
	echo "4 | Query 4"
	echo "5 | Query 5"
	echo "0 | RETURN TO MAIN MENU"
	echo "----------------------------"
	echo "Please enter the number corresponding to the selection above: " 
	read SELECTION

	#Select and run user queries
	case $SELECTION in
		1)
			#Price of product
			echo "Enter the Product ID:"
			read ID 
			db2 "SELECT Name, SKU FROM Product WHERE SKU = $ID"
			;;
		2)
			#Query 2
			
			;;
		3)
			#Query 3
			
			;;
		4)
			#Query 4

			;;
		5)
			#Query 5

			;;
		0)
			#Return to Main Menu
			SELECTION=0
			;;
		*)
			#If user enters soemthing that is NOT part of the selection
			echo "ERROR: Please ONLY enter the selection numbers."
			echo " "
			SELECTION=-1
			;;
	esac
done
