#!/bin/ksh

db2 connect to db2data > /dev/null

#drop tables
echo "[DB2] Drop Tables:..."
db2 "DROP TABLE Product"
db2 "DROP TABLE Sale"
db2 "DROP TABLE Prescription"
db2 "DROP TABLE SaleProduct" 
db2 "DROP TABLE PrescriptionProduct"

echo "[DB2] Drop Tables: DONE"
