#!/bin/ksh
#DB2 Pharmacy - Main Menu

db2 connect to db2data > /dev/null

SELECTION=-1
# Will print infinitely until the user enters 0 to exit the program.
while [ $SELECTION -ne 0 ]
do
	SELECTION=-1
	#Print Main Menu
	echo "----<USER SELECTION MENU>----"
	echo "1 | Administrators"
	echo "2 | Pharmacists"
	echo "3 | Employees"
	echo "4 | Customers"
	echo "0 | EXIT DATABASE"
	echo "----------------------------"
	echo -n "Please enter the number corresponding to the selection above: " ; read SELECTION

	#Select and run next script to run that user queries
	case $SELECTION in
		1)
			#Start Admin script with associated queries
			./DB2Admin
			;;
		2)
			#Start Pharmacists script with associated queries
			./DB2Pharmacist
			;;
		3)
			#Start Cashier script with associated queries
			./DB2Employee
			;;
		4)
			#Start Customer script with associated queries
			./DB2Customer
			;;
		0)
			#Check if user wants to exit
			echo "Are you sure you want to exit?"
			echo -n "Enter 'Yes' to exit (Enter anything to return to MAIN MENU): " ; read exit_message
			if [ "$exit_message" = "Yes" ]
			then
				SELECTION=0
			else
				SELECTION=-1
			fi
			;;
		*)
			#If user enters soemthing that is NOT part of the selection
			echo "ERROR: Please ONLY enter the selection numbers."
			echo " "
			SELECTION=-1
			;;
	esac
done
