#!/bin/ksh

db2 connect to db2data > /dev/null

echo "[DB2] Populating Tables..."
db2 "INSERT INTO EMPLOYEE VALUES (1, 'Kevin', 'kevin1.furtado@ryerson.ca', 'kfurtado', '******', 'First computer?', '*********', 100, 1, 1)"
db2 "INSERT INTO EMPLOYEE VALUES (2, 'Oskar', 'Oskar.hanson@ryerson.ca', 'ohanson', '******', 'Favourite Teacher?', '*********', 100, 1, 1)"
db2 "INSERT INTO EMPLOYEE VALUES (3, 'Zack', 'zharris@ryerson.ca', 'zharris', '******', 'First Car?', '*********', 100, 1, 1)"
db2 "INSERT INTO EMPLOYEE VALUES (4, 'Dante', 'dcamaren@ryerson.ca', 'dcamaren', '******', 'First Pet?', '*********', 100, 1, 1)"

db2 "INSERT INTO PRODUCT VALUES (1, 4598, 'Tylenol', 4.00, 6.99, 50, '09/02/2015', 'Warehouse', 'Main cabinet', '09/02/2014',NULL)"
db2 "INSERT INTO PRODUCT VALUES (2, 654, 'Cough syrup', 8.00, 11.99, 25, '04/25/2015', 'Warehouse', 'Secondary cabinet', '09/14/2014',NULL)"
db2 "INSERT INTO PRODUCT VALUES (3, 598, 'Hydrocodone', 30.50, 60.99, 25, '09/20/2017', 'In Store', '1st aisle', '09/02/2014',NULL)"
db2 "INSERT INTO PRODUCT VALUES (4, 120, 'Lisinopril', 25.50, 39.95, 0, '02/15/2017', 'In Store', '3rd aisle', '09/07/2014', '10/02/2014')"

db2 "INSERT INTO ORDERSET VALUES (1,1,'09/14/2014')"
db2 "INSERT INTO ORDERSET VALUES (2,0,'10/02/2014')"
db2 "INSERT INTO ORDERSET VALUES (3,0,'11/15/2014')"
db2 "INSERT INTO ORDERSET VALUES (4,0,'10/03/2014')"

db2 "INSERT INTO CUSTOMER VALUES (1,4,'Prof. Mastoras','amastora@ryerson.ca',5.00,'213 burgundy st','4500-0569-9878-5566')"
db2 "INSERT INTO CUSTOMER VALUES (2,1,'Joseph Chapman','Joseph11@gmail.com',25.00,'527 Orillia st','4500-8585-5950-0982')"
db2 "INSERT INTO CUSTOMER VALUES (3,2,'Heather Fisher','Heather_09@gmail.com',50.00,'23 university ave','4595-5593-8675-5958')"
db2 "INSERT INTO CUSTOMER VALUES (4,1,'Lisa James','Lisa1_99@gmail.com',98.00,'705 king st','4500-9444-3455-3455')"

db2 "INSERT INTO ORDER VALUES (1, 1, 1, 1)"
db2 "INSERT INTO ORDER VALUES (2, 2, 1, 1)"
db2 "INSERT INTO ORDER VALUES (3, 1, 2, 3)"
db2 "INSERT INTO ORDER VALUES (4, 2, 4, 6)"

db2 "INSERT INTO PRESCRIPTION VALUES (1,2,3,1,1,'Dr Mastoras',4,200)"
db2 "INSERT INTO PRESCRIPTION VALUES (2,3,4,3,2,'Dr Davis',2,145)"
db2 "INSERT INTO PRESCRIPTION VALUES (3,3,4,2,1,'Dr Davis',2,399)"
db2 "INSERT INTO PRESCRIPTION VALUES (4,4,4,1,1,'Dr Marin',2,122)"

db2 "INSERT INTO INCOMESTATEMENT VALUES (1,1770.00,420.00,50.00,900,0.00,'Current Asset','09/01/2014')"
db2 "INSERT INTO INCOMESTATEMENT VALUES (2,2433.00,600.00,75.00,1000.00,8.00,'Current Liabilities','10/01/2014')"
db2 "INSERT INTO INCOMESTATEMENT VALUES (3,2365.00,800.00,100.00,1100.00,15.00,'Current Asset','11/01/2014')"
db2 "INSERT INTO INCOMESTATEMENT VALUES (4,3120.00,950.00,150.00,1200.00,20.00,'Shortterm Asset','12/01/2014')"

db2 "INSERT INTO EQUITY VALUES (1,'12/01/2014',1500.00,800.00,2300.00)"
db2 "INSERT INTO EQUITY VALUES (2,'11/01/2014',1150.00,350.00,1500.00)"
db2 "INSERT INTO EQUITY VALUES (3,'10/01/2014',400.00,750.00,1150.00)"
db2 "INSERT INTO EQUITY VALUES (4,'09/01/2014',0.00,400.00,400.00)"

db2 "INSERT INTO BALANCESHEET VALUES (1,1500.00,250.00,'22 garrison ave',1000.00,500.00,750.00,350.00,'09/01/2014','Pharmacy Logo')"
db2 "INSERT INTO BALANCESHEET VALUES (2,2100.00,350.00,'22 garrison ave',1500.00,500.00,750.00,350.00,'10/01/2014','Pharmacy Logo')"
db2 "INSERT INTO BALANCESHEET VALUES (3,3500.00,550.00,'22 garrison ave',1700.00,500.00,750.00,350.00,'11/01/2014','Pharmacy Logo')"
db2 "INSERT INTO BALANCESHEET VALUES (4,4500.00,450.00,'22 garrison ave',1900.00,900.00,750.00,350.00,'12/01/2014','Pharmacy Logo')"

echo "[DB2] Populating Tables: DONE"
