#!/bin/ksh
#DB2 Pharmacy - Pharmacist Script

db2 connect to db2data > /dev/null

SELECTION=-1
# Will print infinitely until the user enters 0 to exit the previous Script.
while [ $SELECTION -ne 0 ]
do
	SELECTION=-1
	#Print Pharmacist Menu
	echo "----<PHARMACIST MENU>----"
	echo "1 | View all Prescriptions"
	echo "2 | Queue of pending Prescriptions"
	echo "3 | Fill a Prescription"
	echo "0 | RETURN TO MAIN MENU"
	echo "----------------------------"
	echo -n "Please enter the number corresponding to the selection above: " ; read SELECTION

	#Select and run user queries
	case $SELECTION in
		1)
			#View All Prescriptions
			db2 "SELECT * FROM Prescription"
			;;
		2)
			#Queue of pending Prescriptions
			db2 "SELECT * FROM Prescription WHERE isFulfilled = 0 ORDER BY DateOrdered FETCH FIRST 5 ROWS ONLY"
			;;
		3)
			#Place an order for a pending prescription
			echo -n "Enter the Prescription ID: " ; read sale_id
			echo -n "The Products in this prescription are as follows: " ;
			db2 "SELECT Name, Stock, Department, Price FROM Product
			INNER JOIN PrescriptionProduct
			ON PrescriptionProduct.PrescriptionID = $sale_id
			AND Product.SKU = PrescriptionProduct.ProductSKU"

			echo -n "Once you have ordered the products above please enter 'Yes to confirm': " ; read message
			if [ "$message" = "Yes" ]
				then
					db2 "UPDATE Prescription SET DateDelivered=current timestamp, isFulfilled= 1 WHERE ID = $sale_id" > /dev/null
					echo "The prescription with the id $sale_id has been filled.";
			fi
			;;
		0)
			#Return to Main Menu
			SELECTION=0
			;;
		*)
			#If user enters soemthing that is NOT part of the selection
			echo "ERROR: Please ONLY enter the selection numbers."
			echo " "
			SELECTION=-1
			;;
	esac
done
