#!/bin/bash
#Give permmissions needed to the files
chmod -R 775 DB2Files/ > /dev/null
chmod 775 DB2Pharmacy

echo "[INITIALIZING] Zipping files..."
# Compress all the nessary files to be sent make sure all files accounted for
zip -r DB2Pharmacy.zip DB2Files/ > /dev/null

#Send to turing then connect to turing
echo "[INITIALIZING] Loading files into turning directory."
scp DB2Pharmacy.zip DB2Pharmacy k3furtad@turing.acs.ryerson.ca:~/ > /dev/null
echo "[INITIALIZING] Files loaded."
echo "[INITIALIZING] Connecting to turing."
ssh k3furtad@turing.acs.ryerson.ca './DB2Pharmacy'

